version : '4.8'

services:
  nginx:
    image:  nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ayush-global-env:/var/www/html:delegated
  mysql:
    image:  mysql:latest
    environment:
      MYSQL_DATABASE: ag
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - mysql:mysql
    ports:
      - "8060:80"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      PMA_HOST: mysql
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./ayush-global-env:/var/www/html:delegated